### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MonoAdrian23** [wode490390/OceanMonumentPopulator#2]
Hello Wodor, thank you very much for this great Template Addons.
Please add a Plugin for Jungle and Desert Temples.

**Comment by wode490390** [comment]
All structure populators:
- **`Desert Pyramid`, `Jungle Pyramid` and `Swamp Hut`: https://github.com/wode490390/ScatteredBuildingPopulator**
- `Dungeon` and `Desert Well`: https://github.com/wode490390/QuasiStructurePopulator
- `Fossil` and `Shipwreck`: https://github.com/wode490390/SingleTemplateStructurePopulator
- `Igloo`, `Ocean Ruins` and `Pillager Outpost`: https://github.com/wode490390/MultiTemplateStructurePopulator
- `Mineshaft`: https://github.com/wode490390/MineshaftPopulator
- `Stronghold`: https://github.com/wode490390/StrongholdPopulator
- `Nether Fortress`: https://github.com/wode490390/NetherFortressPopulator
- `Ocean Monument`: https://github.com/wode490390/OceanMonumentPopulator
- `Village`: https://github.com/wode490390/ClassicVillagePopulator
- `Woodland Mansion`: *WIP*
- `End City`: *WIP*

**Comment by MonoAdrian23** [comment]
Sorry Wodor, i have find it.
Sorry for waste youre time.
Thank you very much
